### PR TITLE
fix dockerfile so it can build successfully

### PR DESCRIPTION
**Pull request by jiangao1**
Solved the build problem in https://github.com/kantancoding/microservices-python/issues/31

### CODE REVIEW

**Comment by kantancoding** [comment]
Hi, can you write a description of what the issue was and exactly what your change does and how this solves the problem?

**Comment by jiangao1** [comment]
Sure. When I run the docker build command with the existing Dockerfile in src/auth, the build fails with the error message: ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir --requirement /app/requirements.txt"

Following the suggestions in the issue #31 by adding pkg-config, the docker build then becomes successful. I'm using M2 Mac, not sure if it has something to do with that.

**Comment by kantancoding** [comment]
> Sure. When I run the docker build command with the existing Dockerfile in src/auth, the build fails with the error message: ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir --requirement /app/requirements.txt"
> 
> 
> 
> Following the suggestions in the issue #31 by adding pkg-config, the docker build then becomes successful. docker version I have is 25.0.3

I see. Can you tell me what pkg-config does?

**Comment by jiangao1** [comment]
I'm not quite familiar with how it works, but from what I can gather, pkg-config is a tool that helps ensure compiler options are correct when compiling and linking software. It seems it helps to find where libraries are without knowing their exact path. https://www.freedesktop.org/wiki/Software/pkg-config/

**Review by kantancoding — APPROVED** [review]

**Comment by kantancoding** [comment]
> I'm not quite familiar with how it works, but from what I can gather, pkg-config is a tool that helps ensure compiler options are correct when compiling and linking software. It seems it helps to find where libraries are without knowing their exact path. https://www.freedesktop.org/wiki/Software/pkg-config/

Got it! @jiangao1 Thank you!

**Pull request merged**
